api/urls.py
from django.urls import path
from api import views

app_name = "api"


urlpatterns = [
    
]

cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

home/urls.py
from django.urls import path
from home import views
from .views import *

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', CustomLoginView.as_view(), name='login'),    
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('logout/', views.LogOut.as_view(), name="logout"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('rutas/', views.Rutas.as_view(), name="rutas"),
    path('horarios1/', views.Horarios1.as_view(), name="horarios1"),
    path('horarios2/', views.Horarios2.as_view(), name="horarios2"),
    path('horarios3/', views.Horarios3.as_view(), name="horarios3"),
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('formal/', views.Formal.as_view(), name="formal"),
    path('polo/', views.Polo.as_view(), name="polo"),
    path('tazas/', views.Tazas.as_view(), name="tazas"),
    path('gorras/', views.Gorras.as_view(), name="gorras"),
    path('unidades/', views.Unidades.as_view(), name="unidades"),
    path('horarios1/', Horarios1.as_view(), name='horarios1'),
    path('horarios2/', Horarios2.as_view(), name='horarios2'),
    path('horarios3/', Horarios3.as_view(), name='horarios3'),
]

home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser, BaseUserManager

#### CUSTOM USER MANAGER ####

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

#### USER ####

class User(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    
    groups = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        related_name="custom_user_groups",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        related_name="custom_user_permissions",
    )

#### USER PROFILE ####

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    bio = models.CharField(max_length=256, default="I love this app")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.user.first_name

#### EMPLEADOS ####

class Empleados(models.Model):
    NoEmpleado = models.IntegerField()
    NombrePila = models.CharField(max_length=50)
    PrimerApellido = models.CharField(max_length=50)
    SegundoApellido = models.CharField(max_length=50)
    Calle = models.CharField(max_length=100)
    NumExt = models.CharField(max_length=10)
    Colonia = models.CharField(max_length=50)
    NumTel = models.CharField(max_length=15)

    def __str__(self):
        return self.NombrePila

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import UserProfile  

#### SIGNUP ####

class SignUpForm(UserCreationForm):
    username = forms.CharField(label='Nombre de usuario', max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escriba su nombre de usuario"}))
    password1 = forms.CharField(label='Ingrese su contraseña', max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escriba su contraseña"}))
    password2 = forms.CharField(label='Ingrese su contraseña nuevamente', max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Repita su contraseña"}))
    email = forms.CharField(label='Correo electronico', max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escriba tu email"}))
    first_name = forms.CharField(label='Nombre', max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escriba su nombre"}))
    last_name = forms.CharField(label='Apellido', max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escriba su apellido"}))
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "email",
            "first_name",
            "last_name"
           
        ]

#### LOGIN ####

class LoginForm(forms.Form):
    username = forms.CharField(label='Nombre de usuario', max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escriba su nombre de usuario"}))
    password = forms.CharField(label='Ingrese su contraseña', max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escriba su contraseña"}))

#### USER PROFILE ####

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            "user",
            "bio",
            "status"
        ]
        widgets = {
            "user": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "bio": forms.Textarea(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe acerca de ti", "row":3}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
        }

home/views.py
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from .forms import *
from .models import UserProfile
from django.views.generic import FormView

class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    form_class = SignUpForm
    #success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        user = form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return HttpResponseRedirect(self.get_success_url(), user.id)

    def get_success_url(self) -> str:
        pk = self.kwargs[pk]
        return reverse("home:detail_userprofile", kwargs={"pk": pk})    
    


class DetailUserProfile(LoginRequiredMixin, generic.View):
    template_name = "home/detail_userprofile.html"
    context = {}
    login_url = "/"

    def get(self, request, pk):
        self.context = {
            "profile": UserProfile.objects.get(id=pk)
        }
        return render(request, self.template_name,self.context)
    
class UpdateUserProfile(LoginRequiredMixin, generic.UpdateView):
    template_name = "home/update_userprofile.html"
    model = UserProfile
    form_class = UserProfileForm
    success_url = reverse_lazy("home:detail_userprofile")
    login_url = "/"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("home:detail_userprofile", kwargs={"pk":pk})



class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return redirect("/")

    

class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)


class Identity(generic.View):
    template_name = "home/identity.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)


class Contact(generic.View):
    template_name = "home/contact.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
class Rutas(generic.View):
    template_name = "home/rutas.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
class Empleados(generic.View):
    template_name = "home/forms.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
class LogOut(generic.View):
    def get(self, request):
        logout(request)
        return redirect("/")



class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return redirect("/")

class CustomLoginView(FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm  # Utiliza tu formulario de inicio de sesión
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        # Lógica adicional después del inicio de sesión exitoso
        user = authenticate(
            self.request,
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )

        if user is not None:
            login(self.request, user)

        return redirect("/")



class CreateUserProfile(LoginRequiredMixin, generic.CreateView):
    template_name = "home/user_profile.html"
    model = UserProfile
    form_class = UserProfileForm
    success_url = reverse_lazy("home:user_profile")
    login_url = "/"


class Formal(generic.View):
    template_name = "home/formal.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)


class Polo(generic.View):
    template_name = "home/polo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)

class Tazas(generic.View):
    template_name = "home/tazas.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
class Gorras(generic.View):
    template_name = "home/gorras.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
class Unidades(generic.View):
    template_name = "home/unidades.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Enrique Flores"
        }
        return render(request, self.template_name, self.context)
    
    
def is_superuser(user):
    return user.is_superuser



# Consultas

# views.py

class Horarios1(generic.TemplateView):
    template_name = "home/horarios1.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        with connection.cursor() as cursor:
            cursor.execute("""
                select DISTINCT
                    p.Nombre as Paradas,
                    p.Descripcion as Descripcion
                    from Rutas as r
                    inner join Paradas as p on r.Parada = p.Clave
                    where r.`Nombre` = "5 y 10"
            """)

            rutas_data = cursor.fetchall()

        context['rutas1'] = rutas_data

        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 101
            """)

            rutas_data2 = cursor.fetchall()

        context['rutas11'] = rutas_data2

        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 104
            """)

            rutas_data3 = cursor.fetchall()

        context['rutas111'] = rutas_data3
        
        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 107
            """)

            rutas_data4 = cursor.fetchall()

        context['rutas1111'] = rutas_data4

        return context


    
    
    
    
    

class Horarios2(generic.TemplateView):
    template_name = "home/horarios2.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        with connection.cursor() as cursor:
            cursor.execute("""
                select DISTINCT
                    p.Nombre as Paradas,
                    p.Descripcion as Descripcion
                    from Rutas as r
                    inner join Paradas as p on r.Parada = p.Clave
                    where r.`Nombre` = "Natura"
            """)

            rutas_data = cursor.fetchall()

        context['rutas2'] = rutas_data

        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 102
            """)

            rutas_data2 = cursor.fetchall()

        context['rutas22'] = rutas_data2

        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 105
            """)

            rutas_data3 = cursor.fetchall()

        context['rutas222'] = rutas_data3
        
        with connection.cursor() as cursor:
            cursor.execute("""
                select
                Hora
                from Rutas
                where `NoRuta` = 108
            """)

            rutas_data4 = cursor.fetchall()

        context['rutas2222'] = rutas_data4

        return context



class Horarios3(generic.TemplateView):
    template_name = "home/horarios3.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        with connection.cursor() as cursor:
            cursor.execute("""
                select DISTINCT

templates/home/contact.html
{% extends "base/baseadmin.html" %}

{% block title %}
Gestion de Rutas
{% endblock %}

{% block content %}
<h1>Hola {{ name }} Bienvenido a About XD</h1>
<a href="{% url 'home:about' %}" class="btn btn-outline-danger">Ver rutas</a>
{% endblock %}

{% block navbar %}
{{ block.super }}
<li class="nav-item">
  <a href="https://www.youtube.com/watch?v=7LhwRtwEDvw" class="nav-link disabled" aria-disabled="true">Disabled</a>
</li>
{% endblock %}

templates/home/formal.html
{% extends 'base/baseadmin.html' %}
{% load static %}
{% block title %}
Detalles del Producto
{% endblock %}

{% block content %}
<style>
  .product-image-container {
    overflow: hidden;
    position: relative;
  }

  .product-image {
    transition: transform 0.3s ease-in-out;
  }

  .product-image:hover {
    transform: scale(1.2);
  }

  .zoom-img {
    transition: transform 0.5s;
  }

  .zoom-img:hover {
    transform: scale(2);
  }
</style>

<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 product-image-container">
      <img src="{% static 'img/Formal.jpg' %}" class="img-fluid product-image zoom-img" alt="Producto 1"
        onmousemove="zoomImage(event)" />
    </div>

    <div class="col-md-6 text-white">
      <h2 class="text-center">Camisa de manga larga </h2>
      <h2 class="text-center">"Joint Koders Alliance"</h2>
      <p class="text-center">Camiseta de manga larga formal de la empresa "Joint Koders Alliance"</p>
      <p class="text-center">Precio unitario: $20.00 MXN</p>

      <form action="{% url 'home:rutas' %}" method="post" class="text-center">
        {% csrf_token %}
        <label for="cantidad">Cantidad:</label>
        <input type="number" id="cantidad" name="cantidad" value="1" min="1" />
      </form>
      <div class="mt-2"></div>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" class="text-center">
        <input type="hidden" name="cmd" value="_s-xclick" />
        <input type="hidden" name="hosted_button_id" value="ZGG3QKYKSU6TW" />
        <input type="hidden" name="currency_code" value="MXN" />
        <input type="image" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_buynowCC_LG.gif" border="0"
          name="submit" title="PayPal es una forma segura y fácil de pagar en línea." alt="Comprar ahora" />
      </form>
      <div class="mt-3 text-center">
        <a href="/" class="btn btn-outline-light">Volver</a>
      </div>
    </div>
  </div>
</div>

<script>
  function zoomImage(event) {
    const img = event.currentTarget
    const boundingRect = img.getBoundingClientRect()

    const mouseX = event.clientX - boundingRect.left
    const mouseY = event.clientY - boundingRect.top

    const percentX = mouseX / boundingRect.width
    const percentY = mouseY / boundingRect.height

    img.style.transformOrigin = `${percentX * 100}% ${percentY * 100}%`
  }
</script>
{% endblock %}

templates/home/gorras.html
{% extends 'base/baseadmin.html' %}
{% load static %}
{% block title %}
Detalles del Producto
{% endblock %}

{% block content %}
<style>
  .product-image-container {
    overflow: hidden;
    position: relative;
  }

  .product-image {
    transition: transform 0.3s ease-in-out;
  }

  .product-image:hover {
    transform: scale(1.2);
  }

  .zoom-img {
    transition: transform 0.5s;
  }

  .zoom-img:hover {
    transform: scale(2);
  }
</style>

<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 product-image-container">
      <img src="{% static 'img/Proximamente.jpg' %}" class="img-fluid product-image zoom-img" alt="Producto 2"
        onmousemove="zoomImage(event)" />
    </div>

    <div class="col-md-6 text-white">
      <h2 class="text-center">Gorra</h2>
      <h2 class="text-center">"Joint Koders Alliance"</h2>
      <p class="text-center">Gorra personalizada de la empresa "Joint Koders Alliance"</p>
      <p class="text-center">Precio unitario: $20.00 MXN</p>

      <form action="{% url 'home:rutas' %}" method="post" class="text-center">
        {% csrf_token %}
        <label for="cantidad">Cantidad:</label>
        <input type="number" id="cantidad" name="cantidad" value="1" min="1" />
      </form>
      <div class="mt-2"></div>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" class="text-center">
        <input type="hidden" name="cmd" value="_s-xclick" />
        <input type="hidden" name="hosted_button_id" value="ZGG3QKYKSU6TW" />
        <input type="hidden" name="currency_code" value="MXN" />
        <input type="image" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_buynowCC_LG.gif" border="0"
          name="submit" title="PayPal es una forma segura y fácil de pagar en línea." alt="Comprar ahora" />
      </form>
      <div class="mt-3 text-center">
        <a href="/" class="btn btn-outline-light">Volver</a>
      </div>
    </div>
  </div>
</div>

<script>
  function zoomImage(event) {
    const img = event.currentTarget
    const boundingRect = img.getBoundingClientRect()

    const mouseX = event.clientX - boundingRect.left
    const mouseY = event.clientY - boundingRect.top

    const percentX = mouseX / boundingRect.width
    const percentY = mouseY / boundingRect.height

    img.style.transformOrigin = `${percentX * 100}% ${percentY * 100}%`
  }
</script>
{% endblock %}

templates/home/horarios1.html
{% extends "base/baseadmin.html" %}

{% load static %}

{% block title %}
Gestion de Rutas - Horarios 1
{% endblock %}

{% block content %}
<div class="container text-center">
  <h1>Ruta - Zona Centro</h1>
  <div class="row mt-3">
    <div class="col">

      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Paradas</th>
            <th scope="col">Descripción</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas1 %}
          <tr>
            <td>{{ ruta.0 }}</td>
            <td>{{ ruta.1 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col" style="max-width: 57px;">
      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Mat</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas11 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col" style="max-width: 57px;">
      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Vesp</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas111 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col" style="max-width: 0px;">
      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Noct</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas1111 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <a href="{% url 'home:rutas' %}" class="btn btn-outline-dark form-control mt-3">Volver</a>
</div>
{% endblock %}

templates/home/horarios2.html
{% extends "base/baseadmin.html" %}

{% load static %}

{% block title %}
Gestion de Rutas - Horarios 2
{% endblock %}

{% block content %}
<div class="container text-center">
  <h1>Ruta - Natura</h1>
  <div class="row mt-3">
    <div class="col">

      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Paradas</th>
            <th scope="col">Descripción</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas2 %}
          <tr>
            <td>{{ ruta.0 }}</td>
            <td>{{ ruta.1 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col" style="max-width: 57px;">
      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Mat</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas22 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col" style="max-width: 57px;">
      <table class="table table-bordered text-white">
        <thead>/* Ajusta el factor de escala según tus preferencias */
          <tr>
            <th scope="col">Vesp</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas222 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col" style="max-width: 0px;">
      <table class="table table-bordered text-white">
        <thead>
          <tr>
            <th scope="col">Noct</th>
          </tr>
        </thead>
        <tbody>
          {% for ruta in rutas2222 %}
          <tr>
            <td>{{ ruta.0 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <a href="{% url 'home:rutas' %}" class="btn btn-outline-dark form-control mt-3">Volver</a>
</div>
{% endblock %}

templates/home/rutas.html
{% extends 'base/baseadmin.html' %}

{% load static %}

{% block title %}
Gestion de Rutas
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center mt-5" style="height: 10vh;">
  <div class="card border-black border pricing-card-body text-center mx-4"
    style="--bs-card-bg: #264550; width: 300px; height: 300px; border-radius: 25px;">
    <div class="text-center pricing-card-head mt-4">
      <h3 class="text-white">Ruta - Zona Centro</h3>
      <img src="{% static 'img/LogoC.png' %}" style="height: 80px; width: 80px; margin-top: 4px;" alt="product image"
        width="150" height="150" />
    </div>

    <div class="mt-3">
      <a href="https://maps.app.goo.gl/fvNxsCHJManHicur9" target="blank" class="btn btn-outline-light">Ver Ruta</a>
    </div>
    <div class="mt-3">
      <a href="{% url 'home:horarios1' %}" class="btn btn-outline-light">Ver Horario</a>
    </div>
  </div>

  <div class="card border-black border pricing-card-body text-center mx-4"
    style="--bs-card-bg: #264550; width: 300px; height: 300px; border-radius: 25px;">
    <div class="text-center pricing-card-head mt-4">
      <h3 class="text-white">Ruta - Natura</h3>
      <img src="{% static 'img/LogoC.png' %}" style="height: 80px; width: 80px; margin-top: 5px;" alt="product image"
        width="150" height="150" />
    </div>

    <div class="mt-3">
      <a href="https://maps.app.goo.gl/KeL5gEDLP24cWGcT6" target="blank" class="btn btn-outline-light">Ver Ruta</a>
    </div>
    <div class="mt-3">
      <a href="{% url 'home:horarios2' %}" class="btn btn-outline-light">Ver Horario</a>
    </div>
  </div>

  <div class="card border-black border pricing-card-body text-center mx-4"
    style="--bs-card-bg: #264550; width: 300px; height: 300px; border-radius: 25px;">
    <div class="text-center pricing-card-head mt-4">
      <h3 class="text-white">Ruta - Villa Fontana</h3>
      <img src="{% static 'img/LogoC.png' %}" style="height: 80px; width: 80px; margin-top: 5px;" alt="product image"
        width="150" height="150" />
    </div>

    <div class="mt-3">
      <a href="https://maps.app.goo.gl/XGfqSHvJQardgV6w8" target="blank" class="btn btn-outline-light">Ver Ruta</a>
    </div>
    <div class="mt-3">
      <a href="{% url 'home:horarios3' %}" class="btn btn-outline-light">Ver Horario</a>
    </div>
  </div>
</div>
{% endblock %}

templates/home/signup.html
{% extends "base/baseadmin.html" %}

{% block title %}
Registrarse
{% endblock title %}

{% block content %}
<divL class="container text-center">
  <h1>Registro</h1>
  <div class="row mt-3">
    <div class="col">
      <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-dark form-control mt-3">Crear usuario</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-dark form-control mt-1">Cancel</a>
      </form>
    </div>
  </div>
  </div>
  {% endblock content %}