api/urls.py
from django.urls import path
from api import views

app_name = "api"


urlpatterns = [
    
]

core/urls.py
from django.urls import path
from core import views
from .views import NuevaTuplaRuta

app_name = "core"

urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="gg_create"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="gg_detail"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="gg_update"),
    path('list/routes/', views.ListRoutes.as_view(), name="list_routes"),
    path('create/route/', views.CreateRoute.as_view(), name="route_create"),
    path('route/<int:noruta>/', views.DetailRoute.as_view(), name="route_detail"),
    path('stop/route/<int:numeroconsecutivo>/', views.AddStop.as_view(), name="route_stop"),
    path('delete/route/<int:noruta>', views.DeleteRoute.as_view(), name="route_delete"),
    path('stop/delete/<int:pk>/', views.DeleteStop.as_view(), name="route_stopd"),
    path("list/empleados/", views.ListEmpleados.as_view(), name="list_empleados"),
    path('empleados/<int:pk>/', views.DetailEmpleados.as_view(), name='empleados_detail'),
    path('create/empleado/', views.CreateEmpleado.as_view(), name="empleados_create"),
    path('update/empleado/<int:pk>/', views.UpdateEmpleado.as_view(), name="empleados_update"),
    path('delete/empleados/<int:pk>/', views.DeleteEmpleado.as_view(), name="empleados_delete"),
    path("list/conductores/", views.ListConductores.as_view(), name="list_conductores"),
    path('conductores/<int:pk>/', views.DetailConductores.as_view(), name='conductores_detail'),
    path('create/conductor/', views.CreateConductores.as_view(), name="conductores_create"),
    path('update/conductor/<int:pk>/', views.UpdateConductores.as_view(), name="conductores_update"),
    path('delete/conductores/<int:pk>/', views.DeleteConductores.as_view(), name="conductores_delete"),
    path("list/administradores/", views.ListAdministradores.as_view(), name="list_administradores"),
    path('administradores/<int:pk>/', views.DetailAdministrador.as_view(), name='administrador_detail'),
    path('create/administrador/', views.CreateAdministrador.as_view(), name="administrador_create"),
    path('update/administrador/<int:pk>/', views.UpdateAdministrador.as_view(), name="administrador_update"),
    path('delete/administrador/<int:pk>/', views.DeleteAdminstrador.as_view(), name="administrador_delete"),
    path("list/transportes/", views.ListTransportes.as_view(), name="list_transportes"),
    path('transportes/<int:pk>/', views.DetailTrasporte.as_view(), name='transporte_detail'),
    path('create/transporte/', views.CreateTransporte.as_view(), name="transporte_create"),
    path('update/transporte/<int:pk>/', views.UpdateTransporte.as_view(), name="transporte_update"),
    path('delete/transporte/<int:pk>/', views.DeleteTransporte.as_view(), name="transporte_delete"),
    path("list/paradas/", views.ListParadas.as_view(), name="list_paradas"),
    path('paradas/<int:pk>/', views.DetailParada.as_view(), name= "parada_detail"),
    path('create/paradas/', views.CreateParada.as_view(), name="parada_create"),
    path('update/paradas/<int:pk>/', views.UpdateParada.as_view(), name="parada_update"),
    path('delete/paradas/<int:pk>/', views.DeleteParada.as_view(), name="parada_delete"),
    path('list/transporte/conductor', views.ListConductoresTransportes.as_view(), name="list_conductorestransportes"),
    path('create/transporte/conductor', views.CreateConductorTransporte.as_view(), name="conductortransporte_create"),
    path('delete/transporte/conductor/<int:pk>/', views.DeleteConductorTransporte.as_view(), name="conductortransporte_delete"),
    path('create/transporte/empleado', views.CreateEmpleadoTransporte.as_view(), name="empleadotransporte_create"),
    path('delete/transporte/empleado/<int:pk>/', views.DeleteEmpleadoTransporte.as_view(), name="empleadotransporte_delete"),
    path('list/transporte/empleado', views.ListEmpleadosTransportes.as_view(), name="list_empleadostransportes"),
    path('crear_tupla/<int:id_tupla>/', NuevaTuplaRuta.as_view(), name='crear_tupla'),
   
]

cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

home/urls.py
from django.urls import path
from home import views
from .views import *

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', CustomLoginView.as_view(), name='login'),    
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('logout/', views.LogOut.as_view(), name="logout"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('rutas/', views.Rutas.as_view(), name="rutas"),
    path('horarios1/', views.Horarios1.as_view(), name="horarios1"),
    path('horarios2/', views.Horarios2.as_view(), name="horarios2"),
    path('horarios3/', views.Horarios3.as_view(), name="horarios3"),
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('formal/', views.Formal.as_view(), name="formal"),
    path('polo/', views.Polo.as_view(), name="polo"),
    path('tazas/', views.Tazas.as_view(), name="tazas"),
    path('gorras/', views.Gorras.as_view(), name="gorras"),
    path('unidades/', views.Unidades.as_view(), name="unidades"),
    path('horarios1/', Horarios1.as_view(), name='horarios1'),
    path('horarios2/', Horarios2.as_view(), name='horarios2'),
    path('horarios3/', Horarios3.as_view(), name='horarios3'),
]

templates/base/baseadmin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

  <style>
    body {
      display: flex;
      flex-direction: column;
      margin: 0;
      background-color: #93c3c4;
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
    }

    .container {
      flex: 1;
    }

    .main-content {
      margin: 10px auto 20px;
      display: flex;
      justify-content: center;
    }

    .buttonDU {
      position: fixed;
      bottom: 20px;
      font-size: 20px;
      width: 50px;
      height: 50px;
      border-radius: 50%;
      background-color: #264550;
      color: #fff;
      border: none;
      cursor: pointer;
    }

    #scrollUpBtn {
      left: 20px;
    }

    #scrollDownBtn {
      right: 20px;
    }

    footer {
      padding: 1px;
      flex-shrink: 0;
      width: 100%;
      overflow-y: hidden;
    }

    .footer-content {
      width: 800px;
      margin: 0 auto;
      max-height: 215px;
      overflow-y: hidden;
    }

    body {
      overflow-x: hidden;
      overflow-y: auto;
    }
  </style>
</head>

<body style="display: flex; flex-direction: column; min-height: 100vh; margin: 0;">
  <button id="scrollUpBtn" class="buttonDU" onclick="scrollToTop()">⬆️</button>
  <button id="scrollDownBtn" class="buttonDU" onclick="scrollToBottom()">⬇️</button>
  <div class="container">
    <div class="row">
      <div class="col">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-transparent"> 
          <a class="navbar-brand" href="{% url 'home:index' %}">
              <img src="{% static 'img/LogoC.png' %}" alt="Logo" style="height: 40px;"/>
          </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/#quienesSomos">¿Quiénes somos?</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/#unidades">Unidades</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:rutas' %}">Rutas</a>
                  </li>
                  {% if user.is_superuser %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:list_routes' %}">Lista Rutas</a>
                  </li>
                  {% endif %}
                  {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                      Empleados
                    </a>

                    <ul class="dropdown-menu">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                          href="{% url 'core:list_empleados' %}">Empleados</a>
                      </li> {% if user.is_superuser %}
                      <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                          href="{% url 'core:list_empleadostransportes' %}">Empleados Transp.</a>
                      </li>
                      {% endif %}
                    </ul>
                    {% endif %}
                  </li>
                  {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                      Conductores
                    </a>
                    <ul class="dropdown-menu">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                          href="{% url 'core:list_conductores' %}">Conductores</a>
                      </li>
                      {% if user.is_superuser %}
                      <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                          href="{% url 'core:list_conductorestransportes' %}">Conductores Transp.</a>
                      </li>
                      {% endif %}
                    </ul>
                    {% endif %}
                  </li>
                  {% if user.is_superuser %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                      href="{% url 'core:list_administradores' %}">Administradores</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                      href="{% url 'core:list_transportes' %}">Transportes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:list_paradas' %}">Paradas</a>
                  </li>
                  {% endif %}
                  <li>
                    {% if user.is_superuser %}
                    <a class="nav-link active" aria-current="page"
                      href="http://127.0.0.1:8000/admin/">Administración</a>
                    {% endif %}
                  </li>
                </ul>

              </ul>
              </li>
              </ul>
              </ul>
              </li>
              {% if not request.user.is_authenticated %}
              <button type="button" class="btn btn-outline-light me-2"
                onclick="redirectTo('{% url 'home:login' %}')">Iniciar Sesión</button>
              <button type="button" class="btn btn-outline-light me-2"
                onclick="redirectTo('{% url 'home:signup' %}')">Registrarse</button>
              {% else %}
              <button type="button" class="btn btn-outline-light" onclick="redirectTo('{% url 'home:logout' %}')">Cerrar
                Sesión</button>
              {% endif %}

              <script>
                function redirectTo(url) {
                  if (url) {
                    window.location.href = url;
                  }
                }
              </script>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <div class="main-content">
      {% block content %}
      {% endblock %}
    </div>
    <div class="row align-items-stretch">
      <div class="col">
        <footer class="text-white text-center text-lg-start"
          style="background-color: #264550; display: flex; flex-direction: column; max-width: 1300px; margin: 0 auto; border-radius: 10px;">
          <section class="footer-content">
            <div class="container text-center">
              <div class="row mt-3">
                <div class="col-md-4 col-lg-4 col-xl-4 mb-6 footer-column" style="position: relative;">
                  <h6 align="left" class="text-white text-uppercase fw-bold mb-6">Redes Sociales</h6>
                  <p align="left">
                    <a href="https://www.facebook.com/profile.php?id=61552843885228" target="blank"
                      class="text-reset"><i class="mdi mdi-facebook"></i> Facebook</a>
                  </p>
                  <p align="left">
                    <a href="https://www.instagram.com/jointkodersalliance/" target="blank" class="text-reset"><i
                        class="mdi mdi-instagram"></i> Instagram</a>
                  </p>
                  <p align="left">
                    <a href="https://twitter.com/JointKodersAlli" target="blank" class="text-reset"><i
                        class="mdi mdi-twitter"></i> Twitter</a>
                  </p>
                  <p align="left">
                    <a href="https://www.tiktok.com/@itsakzzl" target="blank" class="text-reset"><i
                        class="mdi mdi-tiktok"></i> TikTok</a>
                  </p>
                </div>

                <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                  <a>
                    <h6 align="left" class="text-white text-uppercase fw-bold mb-6">Productos</h6>
                  </a>
                  <p align="left">
                    <a href="{% url 'home:formal' %}" class="text-reset">Uniforme Formal</a>
                  </p>
                  <p align="left">
                    <a href="{% url 'home:polo' %}" class="text-reset">Uniforme Polo</a>
                  </p>
                  <p align="left">
                    <a href="{% url 'home:tazas' %}" class="text-reset">Tazas</a>
                  </p>
                  <p align="left">
                    <a href="{% url 'home:gorras' %}" class="text-reset">Gorras</a>
                  </p>
                </div>

                <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-6 footer-column" style="position: relative;">
                  <a>
                    <h6 align="left" class="text-white text-uppercase fw-bold mb-6">Contacto</h6>
                  </a>
                  <p align="left">
                    <a href="https://maps.app.goo.gl/n1xBh8oXKmCzzm6b9" target="_blank" class="text-reset"><i
                        class="fas fa-map-marked-alt"></i> Tijuana, BC 11731, MX</a>
                  </p>
                  <p align="left">
                    <a href="mailto:jointkodersalliance@gmail.com" target="_blank" class="text-reset"><i
                        class="mdi mdi-google-maps"></i> jointkodersalliance@gmail.com</a>
                  </p>
                  <p align="left">
                    <a href="https://wa.me/qr/HH2324AHZZJOP1" target="_blank" class="text-reset"><i
                        class="mdi mdi-google-maps"></i> +52 (664) 369 2229</a>
                  </p>
                  <p align="left">
                    <a href="https://wa.me/qr/WPDXGSAZMNV3J1" target="_blank" class="text-reset"><i
                        class="mdi mdi-google-maps"></i> +52 (664) 472 8545</a>
                  </p>
                </div>
              </div>
            </div>
          </section>
        </footer>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function () {
        var maxHeight = 0
        $('.footer-column').each(function () {
          var height = $(this).height()
          if (height > maxHeight) {
            maxHeight = height
          }
        })
        $('.footer-column').height(maxHeight)
      })
    </script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <script>
      function scrollToTop() {
        window.scrollTo({
          top: 0,
          behavior: "smooth"
        });
      }

      function scrollToBottom() {
        window.scrollTo({
          top: document.body.scrollHeight,
          behavior: "smooth"
        });
      }</script>
</body>
</html>