api/urls.py
from django.urls import path
from api import views

app_name = "api"


urlpatterns = [
    
]

core/urls.py
from django.urls import path
from core import views
from .views import NuevaTuplaRuta

app_name = "core"

urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="gg_create"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="gg_detail"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="gg_update"),
    path('list/routes/', views.ListRoutes.as_view(), name="list_routes"),
    path('create/route/', views.CreateRoute.as_view(), name="route_create"),
    path('route/<int:noruta>/', views.DetailRoute.as_view(), name="route_detail"),
    path('stop/route/<int:numeroconsecutivo>/', views.AddStop.as_view(), name="route_stop"),
    path('delete/route/<int:noruta>', views.DeleteRoute.as_view(), name="route_delete"),
    path('stop/delete/<int:pk>/', views.DeleteStop.as_view(), name="route_stopd"),
    path("list/empleados/", views.ListEmpleados.as_view(), name="list_empleados"),
    path('empleados/<int:pk>/', views.DetailEmpleados.as_view(), name='empleados_detail'),
    path('create/empleado/', views.CreateEmpleado.as_view(), name="empleados_create"),
    path('update/empleado/<int:pk>/', views.UpdateEmpleado.as_view(), name="empleados_update"),
    path('delete/empleados/<int:pk>/', views.DeleteEmpleado.as_view(), name="empleados_delete"),
    path("list/conductores/", views.ListConductores.as_view(), name="list_conductores"),
    path('conductores/<int:pk>/', views.DetailConductores.as_view(), name='conductores_detail'),
    path('create/conductor/', views.CreateConductores.as_view(), name="conductores_create"),
    path('update/conductor/<int:pk>/', views.UpdateConductores.as_view(), name="conductores_update"),
    path('delete/conductores/<int:pk>/', views.DeleteConductores.as_view(), name="conductores_delete"),
    path("list/administradores/", views.ListAdministradores.as_view(), name="list_administradores"),
    path('administradores/<int:pk>/', views.DetailAdministrador.as_view(), name='administrador_detail'),
    path('create/administrador/', views.CreateAdministrador.as_view(), name="administrador_create"),
    path('update/administrador/<int:pk>/', views.UpdateAdministrador.as_view(), name="administrador_update"),
    path('delete/administrador/<int:pk>/', views.DeleteAdminstrador.as_view(), name="administrador_delete"),
    path("list/transportes/", views.ListTransportes.as_view(), name="list_transportes"),
    path('transportes/<int:pk>/', views.DetailTrasporte.as_view(), name='transporte_detail'),
    path('create/transporte/', views.CreateTransporte.as_view(), name="transporte_create"),
    path('update/transporte/<int:pk>/', views.UpdateTransporte.as_view(), name="transporte_update"),
    path('delete/transporte/<int:pk>/', views.DeleteTransporte.as_view(), name="transporte_delete"),
    path("list/paradas/", views.ListParadas.as_view(), name="list_paradas"),
    path('paradas/<int:pk>/', views.DetailParada.as_view(), name= "parada_detail"),
    path('create/paradas/', views.CreateParada.as_view(), name="parada_create"),
    path('update/paradas/<int:pk>/', views.UpdateParada.as_view(), name="parada_update"),
    path('delete/paradas/<int:pk>/', views.DeleteParada.as_view(), name="parada_delete"),
    path('list/transporte/conductor', views.ListConductoresTransportes.as_view(), name="list_conductorestransportes"),
    path('create/transporte/conductor', views.CreateConductorTransporte.as_view(), name="conductortransporte_create"),
    path('delete/transporte/conductor/<int:pk>/', views.DeleteConductorTransporte.as_view(), name="conductortransporte_delete"),
    path('create/transporte/empleado', views.CreateEmpleadoTransporte.as_view(), name="empleadotransporte_create"),
    path('delete/transporte/empleado/<int:pk>/', views.DeleteEmpleadoTransporte.as_view(), name="empleadotransporte_delete"),
    path('list/transporte/empleado', views.ListEmpleadosTransportes.as_view(), name="list_empleadostransportes"),
    path('crear_tupla/<int:id_tupla>/', NuevaTuplaRuta.as_view(), name='crear_tupla'),
   
]

cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import GrantGoalForm, UpdateGrantGoalForm
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.shortcuts import render
from django.views.generic.edit import CreateView

##### GRANT GOAL #####

#Create
class CreateGrantGoal(generic.CreateView):
    template_name = "core/gg_create.html"
    model = GrantGoal
    form_class = GrantGoalForm
    success_url = reverse_lazy("core:gg_list")


#List
class ListGrantGoal(generic.View):
    template_name = "core/gg_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = GrantGoal.objects.filter(status=True)
        self.context = {
            "grant_goals": queryset
        }
        return render(request, self.template_name, self.context)


#Detail
class DetailGrantGoal(generic.DetailView):
    template_name = "core/gg_detail.html"
    model = GrantGoal


#Update
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/gg_update.html"
    model = GrantGoal
    form_class = UpdateGrantGoalForm
    success_url = reverse_lazy("core:gg_list")


#Delete
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/gg_delete.html"
    model = GrantGoal
    success_url = reverse_lazy("core:gg_list")


#### RUTAS ####

#Lista
class ListRoutes(generic.TemplateView):
    template_name = "core/list_routes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ruta'] = Rutas.objects.values('noruta').distinct()
        return context
    

#Detail
class DetailRoute(generic.ListView):
    template_name = "core/route_detail.html"
    model = Rutas
    context_object_name = 'ruta'

    def get_queryset(self):
        noruta = self.kwargs['noruta']
        return Rutas.objects.filter(noruta=noruta)
    

#Create
class CreateRoute(generic.CreateView):
    template_name = "core/route_create.html"
    model = Rutas
    form_class = CrearRuta
    success_url = reverse_lazy("core:list_routes")


class DeleteRoute(generic.DeleteView):
    template_name = "core/route_delete.html"
    model = Rutas
    success_url = reverse_lazy("core:list_routes")

    def get_object(self, queryset=None):
        routes = Rutas.objects.filter(noruta=self.kwargs['noruta'])
        return routes 
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        
        if self.object.exists():
            self.object.delete() 
            
        return HttpResponseRedirect(success_url)
    

#### STOP ####

#Create
class AddStop(generic.UpdateView):
    template_name = "core/route_stop.html"
    model = Rutas
    form_class = AddStop
    

    def get_success_url(self):
        return reverse_lazy('core:list_routes')

    def get_object(self, queryset=None):
        return Rutas.objects.get(pk=self.kwargs['numeroconsecutivo'])


class DeleteStop(generic.DeleteView):
    template_name = "core/route_stop_delete.html"
    model = Rutas
    success_url = reverse_lazy("core:list_routes")
  

#### EMPLEADOS ####

#List
class ListEmpleados(generic.TemplateView):
    template_name = "core/list_empleados.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empleado'] = Empleados.objects.all()
        return context


#Detail
class DetailEmpleados(generic.DetailView):
    template_name = "core/empleados_detail.html"
    model = Empleados
    context_object_name = 'empleado'
    success_url = reverse_lazy("core:list_empleados")


#Create
class CreateEmpleado(generic.CreateView):
    template_name = "core/empleados_create.html"
    model = Empleados
    form_class = CrearEmpleado
    success_url = reverse_lazy("core:list_empleados")


#Update
class UpdateEmpleado(generic.UpdateView):
    template_name = "core/empleados_update.html"
    model = Empleados
    form_class = UpdateEmpleado
    success_url = reverse_lazy("core:list_empleados")


#Delete
class DeleteEmpleado(generic.DeleteView):
    template_name = "core/empleados_delete.html"
    model = Empleados
    success_url = reverse_lazy("core:list_empleados")


#### CONDUCTORES ####

#List
class ListConductores(generic.TemplateView):
    template_name = "core/list_conductores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['conductor'] = Conductores.objects.all()
        return context


#Detail
class DetailConductores(generic.DetailView):
    template_name = "core/conductores_detail.html"
    model = Conductores
    context_object_name = 'conductor'
    success_url = reverse_lazy("core:list_conductores")


#Create
class CreateConductores(generic.CreateView):
    template_name = "core/conductores_create.html"
    model = Conductores
    form_class = CreateConductor
    success_url = reverse_lazy("core:list_conductores")


#Update
class UpdateConductores(generic.UpdateView):
    template_name = "core/conductores_update.html"
    model = Conductores
    form_class = UpdateConductor
    success_url = reverse_lazy("core:list_conductores")


#Delete
class DeleteConductores(generic.DeleteView):
    template_name = "core/conductores_delete.html"
    model = Conductores
    success_url = reverse_lazy("core:list_conductores")


#### ADMINISTRADORES ####

#List
class ListAdministradores(generic.TemplateView):
    template_name = "core/list_administradores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['administra'] = Administrador.objects.all()
        return context


#Detail
class DetailAdministrador(generic.DetailView):
    template_name = "core/administrador_detail.html"
    model = Administrador
    context_object_name = 'administra'
    success_url = reverse_lazy("core:list_administradores")


#Create
class CreateAdministrador(generic.CreateView):
    template_name = "core/administrador_create.html"
    model = Administrador
    form_class = CreateAdministrador
    success_url = reverse_lazy("core:list_administradores")


#Update
class UpdateAdministrador(generic.UpdateView):
    template_name = "core/administrador_update.html"
    model = Administrador
    form_class = UpdateAdministrador
    success_url = reverse_lazy("core:list_administradores")


#Delete
class DeleteAdminstrador(generic.DeleteView):
    template_name = "core/administrador_delete.html"
    model = Administrador
    success_url = reverse_lazy("core:list_administradores")


#### TRANSPORTES ####

#List
class ListTransportes(generic.TemplateView):
    template_name = "core/list_transportes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['transporte'] = Transportes.objects.all()
        return context


#Detail
class DetailTrasporte(generic.DetailView):
    template_name = "core/transporte_detail.html"
    model = Transportes
    context_object_name = 'transporte'
    success_url = reverse_lazy("core:list_transportes")


#Create
class CreateTransporte(generic.CreateView):
    template_name = "core/transporte_create.html"
    model = Transportes
    form_class = CreateTransporte
    success_url = reverse_lazy("core:list_transportes")


#Update
class UpdateTransporte(generic.UpdateView):
    template_name = "core/transporte_update.html"
    model = Transportes
    form_class = UpdateTransporte
    success_url = reverse_lazy("core:list_transportes")


#Delete
class DeleteTransporte(generic.DeleteView):
    template_name = "core/transporte_delete.html"
    model = Transportes
    success_url = reverse_lazy("core:list_transportes")


#### PARADAS ####

#List
class ListParadas(generic.TemplateView):
    template_name = "core/list_paradas.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parada'] = Paradas.objects.all()
        return context


#Detail
class DetailParada(generic.DetailView):
    template_name = "core/parada_detail.html"
    model = Paradas
    context_object_name = 'parada'
    success_url = reverse_lazy("core:list_paradas")


#Create
class CreateParada(generic.CreateView):
    template_name = "core/parada_create.html"
    model = Paradas
    form_class = CreateParadas
    success_url = reverse_lazy("core:list_paradas")


#Update
class UpdateParada(generic.UpdateView):
    template_name = "core/parada_update.html"
    model = Paradas
    form_class = UpdateParadas
    success_url = reverse_lazy("core:list_paradas")


#Deete
class DeleteParada(generic.DeleteView):
    template_name = "core/parada_delete.html"
    model = Paradas
    success_url = reverse_lazy("core:list_paradas")


#### EMPLEADO TRANSPORTE ####

#List
class ListEmpleadosTransportes(generic.TemplateView):
    template_name = "core/list_empleadostransportes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empleadotransporte'] = EmpleadosTransp.objects.all()
        return context


#Create
class CreateEmpleadoTransporte(generic.CreateView):
    template_name = "core/empleadotransporte_create.html"
    model = EmpleadosTransp
    form_class = CreateEmpleadoTransporte
    success_url = reverse_lazy("core:list_empleadostransportes")


#Delete
class DeleteEmpleadoTransporte(generic.DeleteView):
    template_name = "core/empleadotransporte_delete.html"
    model = EmpleadosTransp
    success_url = reverse_lazy("core:list_empleadostransportes")


#### CONDUCTOR TRANSPORTE ####

#List
class ListConductoresTransportes(generic.TemplateView):
    template_name = "core/list_conductorestransportes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['conductortransporte'] = ConductoresTransp.objects.all()
        return context


#Create

templates/core/administrador_detail.html
{% extends "base/baseadmin.html" %}

{% block title %} Detalles del administrador {% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Detalles del administrador:</h1>
  <style>
    .table.text-white td,
    .table.text-white th {
      color: white;
    }
  </style>

  <table class="table table-striped table-hover text-white mt-3">
    <thead>
      <tr>
        <th>Numero de adminisrtador</th>
        <th>Nombre de pila</th>
        <th>Apellido paterno</th>
        <th>Apellido materno</th>
        <th>Calle</th>
        <th>Numero exterior</th>
        <th>Colonia</th>
        <th>Telefono</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ administra.noempleado }}</td>
        <td>{{ administra.nombrepila }}</td>
        <td>{{ administra.primerapellido }}</td>
        <td>{{ administra.segundoapellido }}</td>
        <td>{{ administra.calle }}</td>
        <td>{{ administra.numext }}</td>
        <td>{{ administra.colonia }}</td>
        <td>{{ administra.numtel }}</td>
      </tr>
    </tbody>
  </table>

  <div class="text-center">
    <a href="{% url 'core:list_administradores' %}" class="btn btn-outline-dark">Volver</a>
  </div>
</div>
</div>
{% endblock content %}

templates/core/conductores_detail.html
{% extends "base/baseadmin.html" %}

{% block title %} Detalles del conductor {% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Detalles del conductor:</h1>
  <style>
    .table.text-white td,
    .table.text-white th {
      color: white;
    }
  </style>

  <div? class="container mt-3">
    <div class="table table-striped table-hover text-white">
      <table class="styled-table text-white">
        <thead>
          <tr>
            <th>Numero de empleado</th>
            <th>Nombre de pila</th>
            <th>Apellido materno</th>
            <th>Apellido paterno</th>
            <th>Numero de telefono</th>
            <th>Administrador</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ conductor.noempleado }}</td>
            <td>{{ conductor.nombrepila }}</td>
            <td>{{ conductor.primerapellido}}</td>
            <td>{{ conductor.segundoapellido}}</td>
            <td>{{ conductor.numtel}}</td>
            <td>{{ conductor.administrador}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="text-center">
      <a href="{% url 'core:list_conductores' %}" class="btn btn-outline-dark">Volver</a>
    </div>
</div>
</div>
{% endblock content %}

templates/core/empleados_delete.html
{% extends "base/baseadmin.html" %}

{% block title %}
Eliminar
{% endblock title %}

{% block content %}
<style>
  .table.text-white td,
  .table.text-white th {
    color: white;
  }

  .btn-group {
    margin-top: 10px;
  }

  .form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form .form-group label {
    color: white;
  }

  .form-buttons {
    text-align: center;
  }
</style>

<div class="container mt-4">
  <div class="table table-striped table-hover text-white">
    <table class="styled-table text-white">
      <thead>
        <tr>
          <th>¿Está seguro de eliminar al empleado?</th>
        </tr>
      </thead>
    </table>
  </div>

  <form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
      <button type="submit" class="btn btn-outline-dark">Aceptar</button>
      <a href="{% url 'core:list_empleados'%}" class="btn btn-outline-dark">Cancelar</a>
    </div>
  </form>
</div>
{% endblock content %}

templates/core/list_conductores.html
{% extends 'base/baseadmin.html' %}

{% block title %}
Lista de conductores
{% endblock %}

{% block content %}
<div class="container text-center">
  <h1>Lista de conductores:</h1>
  {% if user.is_superuser %}
  <a href="{% url 'core:conductores_create' %}" class="btn btn-outline-dark form-control">Añadir un nuevo conductor</a>
  {% endif %}
  <style>
    .table.text-white td,
    .table.text-white th {
      color: white;
    }
  </style>

  <table class="table table-striped table-hover text-white mt-3">
    <thead>
      <th>Numero de empleado</th>
      <th>Nombre de pila</th>
      <th>Apellido materno</th>
      <th>Apellido paterno</th>
      {% if user.is_superuser %}
      <th></th>
      <th>Acciones</th>
      <th></th>
      {% endif %}
    </thead>
    <tbody>
      {% for Conductores in conductor %}
      <tr>
        <td>{{ Conductores.noempleado }}</td>
        <td>{{ Conductores.nombrepila }}</td>
        <td>{{ Conductores.primerapellido }}</td>
        <td>{{ Conductores.segundoapellido }}</td>
        {% if user.is_superuser %}
        <td>
          <a href="{% url 'core:conductores_detail' Conductores.noempleado %}"
            class="btn btn-outline-light">Detalles</a>
        </td>
        <td>
          <a href="{% url 'core:conductores_update' Conductores.noempleado %}"
            class="btn btn-outline-light">Actualizar</a>
        </td>
        <td>
          <a href="{% url 'core:conductores_delete' Conductores.noempleado %}"
            class="btn btn-outline-light">Eliminar</a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/core/list_transportes.html
{% extends "base/baseadmin.html" %}

{% block title %}Lista de transportes{% endblock title %}

{% block content %}
<tr>
    <div class="container text-center">
        <h1>Lista de transportes:</h1>
        <a href="{% url 'core:transporte_create' %}" class="btn btn-outline-dark form-control">Añade un nuevo
            transporte</a>
        <style>
            .table.text-white td,
            .table.text-white th {
                color: white;
            }
        </style>

        <table class="table table-striped table-hover text-white mt-3">
            <thead>
                <th>Número del transporte</th>
                <th>Matrícula</th>
                <th>Disponibilidad</th>
                <th></th>
                <th>Acciones</th>
                <th></th>

            </thead>
            <tbody>
                {% for Transportes in transporte %}
                <tr>
                    <td>{{ Transportes.notransporte }}</td>
                    <td>{{ Transportes.matricula }}</td>
                    <td>{{ Transportes.disponibilidad}}</td>
                    <td><a href="{% url 'core:transporte_detail' Transportes.notransporte %}"
                            class="btn btn-outline-light"> Detalles </a></td>
                    <td><a href="{% url 'core:transporte_update' Transportes.notransporte %}"
                            class="btn btn-outline-light"> Actualizar </a></td>
                    <td><a href="{% url 'core:transporte_delete' Transportes.notransporte %}"
                            class="btn btn-outline-light"> Eliminar </a></td>

                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
    {% endblock content %}

templates/core/parada_delete.html
{% extends "base/baseadmin.html" %}

{% block title %}Eliminar{% endblock title %}

{% block content %}
<style>
  .table.text-white td,
  .table.text-white th {
    color: white;
  }

  .btn-group {
    margin-top: 10px;
  }

  .form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form .form-group label {
    color: white;
  }

  .form-buttons {
    text-align: center;
  }
</style>

<div class="container mt-4">
  <div class="table table-striped table-hover text-white">
    <table class="styled-table text-white">
      <thead>
        <tr>
          <th>¿Está seguro de eliminar la parada?</th>
        </tr>
      </thead>
    </table>
  </div>

  <form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
      <button type="submit" class="btn btn-outline-dark">Aceptar</button>
      <a href="{% url 'core:list_paradas'%}" class="btn btn-outline-dark">Cancelar</a>
    </div>
  </form>
</div>
{% endblock content %}

templates/core/parada_detail.html
{% extends "base/baseadmin.html" %}

{% block title %} Detalles de la parada{% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Detalles de la parada:</h1>
  <style>
    .table.text-white td,
    .table.text-white th {
      color: white;
    }
  </style>

  <table class="table table-striped table-hover text-white mt-3">
    <thead>
      <tr>
        <th>Clave</th>
        <th>Nombre</th>
        <th>Descripcion</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ parada.clave }}</td>
        <td>{{ parada.nombre }}</td>
        <td>{{ parada.descripcion }}</td>
      </tr>
    </tbody>
  </table>
  <div class="text-center">
    <a href="{% url 'core:list_paradas' %}" class="btn btn-outline-dark">Volver</a>
  </div>
</div>
</div>
</div>
{% endblock content %}

templates/core/parada_update.html
{% extends "base/baseadmin.html" %}

{% block title %}
Actualizar parada
{% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Actualizar parada:</h1>
  <style>
    .btn-group {
      margin-top: 10px;
    }

    .form {
      max-width: 400px;
      margin: 0 auto;
    }

    .form .form-group label {
      color: white;
    }

    .form-buttons {
      text-align: center;
    }
  </style>

  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="form-buttons text-right">
            <button type="submit" class="btn btn-outline-dark">Actualizar</button>
            <a href="{% url 'core:list_paradas' %}" class="btn btn-outline-dark">Cancelar</a>
          </div>
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/core/route_create.html
{% extends "base/baseadmin.html" %}

{% block title %}
Crear ruta
{% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Crear ruta:</h1>

  <form action="" method="post" class="form mt-3"> {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center">
      <button type="submit" class="btn btn-outline-dark">Crear ruta</button>
      <a href="{% url 'core:list_routes' %}" class="btn btn-outline-dark">Cancelar</a>
  </form>
</div>
</div>
{% endblock content %}

templates/core/route_delete.html
{% extends "base/baseadmin.html" %}

{% block title %}
Eliminar ruta
{% endblock title %}

{% block content %}
<style>
  .table.text-white td,
  .table.text-white th {
    color: white;
  }

  .btn-group {
    margin-top: 10px;
  }

  .form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form .form-group label {
    color: white;
  }

  .form-buttons {
    text-align: center;
  }
</style>

<div class="container mt-4">
  <div class="table table-striped table-hover text-white">
    <table class="styled-table text-white">
      <thead>
        <tr>
          <th>¿Está seguro de eliminar la ruta?</th>
        </tr>
      </thead>
    </table>
  </div>
  <form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
      <button type="submit" class="btn btn-outline-dark">Eliminar</button>
      <a href="{% url 'core:list_routes' %}" class="btn btn-outline-dark">Cancelar</a>
    </div>
  </form>
</div>
</div>
{% endblock content %}

templates/core/route_stop_delete.html
{% extends "base/baseadmin.html" %}

{% block title %}
Eliminar
{% endblock title %}

{% block content %}
<style>
  .table.text-white td,
  .table.text-white th {
    color: white;
  }

  .btn-group {
    margin-top: 10px;
  }

  .form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form .form-group label {
    color: white;
  }

  .form-buttons {
    text-align: center;
  }
</style>

<div class="container mt-4">
  <div class="table table-striped table-hover text-white">
    <table class="styled-table text-white">
      <thead>
        <tr>
          <th>¿Está seguro de eliminar la parada?</th>
        </tr>
      </thead>
    </table>
  </div>
  <form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
      <button type="submit" class="btn btn-outline-dark">Aceptar</button>
      <a href="{% url 'core:list_routes'%}" class="btn btn-outline-dark">Cancelar</a>
    </div>
  </form>
</div>
</div>
{% endblock content %}

templates/core/route_update.html
{% extends "base/baseadmin.html" %}

{% block title %}
Actualizar ruta
{% endblock title %}

{% block content %}
<form action="" method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Modificar ruta</button>
  <a href="{% url 'core:list_routes' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

templates/core/transporte_create.html
{% extends 'base/baseadmin.html' %}

{% block title %}
Crear transporte
{% endblock %}

{% block content %}
<style>
  .btn-group {
    margin-top: 10px;
  }

  .form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form-buttons {
    text-align: center;
  }
</style>

<div class="container text-center">
  <h1>Crear transporte:</h1>
  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="form-buttons text-right">
            <button type="submit" class="btn btn-outline-dark">Crear</button>
            <a href="{% url 'core:list_transportes' %}" class="btn btn-outline-dark">Cancelar</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/core/transporte_update.html
{% extends "base/baseadmin.html" %}

{% block title %}
Actualizar transporte
{% endblock title %}

{% block content %}
<div class="container text-center">
  <h1>Actualizar transporte:</h1>
  <style>
    .btn-group {
      margin-top: 10px;
    }

    .form {
      max-width: 400px;
      margin: 0 auto;
    }

    .form .form-group label {
      color: white;
    }

    .form-buttons {
      text-align: center;
    }
  </style>

  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}

          <div class="form-buttons text-right">
            <button type="submit" class="btn btn-outline-dark">Actualizar</button>
            <a href="{% url 'core:list_transportes' %}" class="btn btn-outline-dark">Cancelar</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}